package sigf.mod;

/** Generated by tools/skins.py: extra boxes of each animatronic model {parent, u, v, x, y, z, w, h, d}. */
final class AnimatronicParts {
	private AnimatronicParts() {}

	static final Object[][] FREDDY = {
		{"head", 64, 0, 2.0f, -11.0f, -1.0f, 3.0f, 3.0f, 1.0f},
		{"head", 64, 0, -5.0f, -11.0f, -1.0f, 3.0f, 3.0f, 1.0f},
		{"head", 64, 16, -5.0f, -9.0f, -5.0f, 10.0f, 1.0f, 10.0f},
		{"head", 64, 32, -3.0f, -14.0f, -3.0f, 6.0f, 5.0f, 6.0f},
		{"head", 64, 48, -2.0f, -3.0f, -6.0f, 4.0f, 3.0f, 2.0f},
		{"head", 100, 48, -1.0f, -4.0f, -7.0f, 2.0f, 1.0f, 1.0f},
		{"body", 64, 64, -2.0f, 0.0f, -3.0f, 4.0f, 2.0f, 1.0f},
	};
	static final Object[][] BONNIE = {
		{"head", 64, 0, 1.0f, -19.0f, -0.5f, 2.0f, 11.0f, 1.0f},
		{"head", 64, 0, -3.0f, -19.0f, -0.5f, 2.0f, 11.0f, 1.0f},
		{"head", 64, 48, -2.0f, -3.0f, -6.0f, 4.0f, 3.0f, 2.0f},
		{"head", 100, 48, -1.0f, -4.0f, -7.0f, 2.0f, 1.0f, 1.0f},
		{"body", 64, 64, -2.0f, 0.0f, -3.0f, 4.0f, 2.0f, 1.0f},
	};
	static final Object[][] CHICA = {
		{"head", 64, 0, -3.0f, -10.0f, -1.0f, 2.0f, 3.0f, 2.0f},
		{"head", 64, 0, -1.0f, -11.0f, -1.0f, 2.0f, 3.0f, 2.0f},
		{"head", 64, 0, 1.0f, -10.0f, -1.0f, 2.0f, 3.0f, 2.0f},
		{"head", 64, 48, -3.0f, -3.0f, -8.0f, 6.0f, 2.0f, 4.0f},
		{"head", 100, 48, -2.0f, -1.0f, -7.0f, 4.0f, 1.0f, 3.0f},
		{"body", 64, 64, -3.5f, 0.5f, -3.0f, 7.0f, 9.0f, 1.0f},
	};
	static final Object[][] FOXY = {
		{"head", 64, 0, 2.0f, -11.0f, -1.0f, 3.0f, 3.0f, 1.0f},
		{"head", 64, 0, -5.0f, -11.0f, -1.0f, 3.0f, 3.0f, 1.0f},
		{"head", 64, 48, -2.0f, -4.0f, -9.0f, 4.0f, 2.0f, 5.0f},
		{"head", 100, 48, -2.0f, -2.0f, -8.0f, 4.0f, 1.0f, 4.0f},
		{"head", 64, 96, -2.0f, -2.0f, -9.0f, 4.0f, 1.0f, 1.0f},
		{"right_arm", 64, 80, -1.0f, 10.0f, -0.5f, 1.0f, 4.0f, 1.0f},
		{"right_arm", 100, 80, -1.0f, 13.0f, -2.5f, 1.0f, 1.0f, 2.0f},
	};
}
